### ISSUE TITLE
ServiceWorker behavior?

### ISSUE THREAD

**Issue by bored-engineer** [jonasstrehle/supercookie#1]
In your research have you explored the behavior when combined with ServiceWorkers? Possibly because it could remove the need for a server altogether by "spoofing" URLs under a specific prefix, but also because it can reduce round trip to the server by generating the response within the worker itself locally.

**Comment by jonasstrehle** [comment]
> In your research have you explored the behavior when combined with ServiceWorkers? Possibly because it could remove the need for a server altogether by "spoofing" URLs under a specific prefix, but also because it can reduce round trip to the server by generating the response within the worker itself locally.

Could you elaborate on that idea? I don't understand exactly what you are referring to tbh.
