### ISSUE TITLE
Not Working When cookies are disabled

### ISSUE THREAD

**Issue by TimWilliams-a** [jonasstrehle/supercookie#15]
Your solution is supposed to work without cookies enabled, but when I turn on the Block all cookies flag on Safari I am getting an endless redirect loop on demo.supercookie.me and on my local nodejs project.
It looks like you are highly reliant on cookies.

**Comment by jonasstrehle** [comment]
Yes, you‘re right! To identify the user while the Read/Write process, supercookie makes use of temporary cookies. 
Please note that these cookies wouldn‘t be necessary for this attack scenario at all. Some similar practice like identifying clients via IP header would also work.

**Comment by TimWilliams-a** [comment]
A great idea is to document if this solution would work on third-party iframes.
I wasn't able to get a favicon request from an iframe in Safari for example (and I've tried with HTML favicon as well as with JS)
Have you tried that?

**Comment by jonasstrehle** [comment]
Yeah I already tested a solution via iframes - but it didn't seem to work. 
By the way: When loading favicons via JS, your browser does not access the local F-cache, but sends a GET request to the webserver. Fingerprinting becomes impossible here (except a workaround I've found that is just working fine in [Chrome](https://github.com/jonasstrehle/supercookie/blob/main/server/www/referrer-v2.html))!
Another approach I'm working on is favicon-fingerprinting based on [portals](https://www.chromestatus.com/feature/4828882419056640). I'm going to check this out!

**Comment by TimWilliams-a** [comment]
Nice! I am testing some stuff too on iframes, kind of hard with ITP.
If you want to work together on leads I would love to.
I am checking Web Bluetooth and Proximity Sensor

**Comment by jonasstrehle** [comment]
Sure feel free to contact me on Twitter or via email.

**Comment by TimWilliams-a** [comment]
Email was sent.
