### ISSUE TITLE
Can't fully reproduce with Firefox 85

### ISSUE THREAD

**Issue by AlphaJack** [jonasstrehle/supercookie#2]
I can't reproduce my IDs with Firefox 85 (Linux). I don't know if it is related to [this](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/), they only mention **cross-site** supercookie protection.

Chromium 88 seems to be still vulnerable.
Tabs underlined in blue are part of the same container (Firefox extension), others (left to right) are vanilla Firefox, private Firefox and vanilla Chromium.

First try:
![first-run](https://user-images.githubusercontent.com/19962243/107144164-334e1000-6931-11eb-9f9f-d7a9f96bc2cc.png)

After restarting my browsers:
![second-run](https://user-images.githubusercontent.com/19962243/107144163-32b57980-6931-11eb-924d-f87cba1128bd.png)

**Comment by arobase-che** [comment]
Can't totaly reproduce on Firefox 85.  
Works when I check my id a second time. Failed to retrieve it if I close Firefox.

I got the option "Delete cookies and site data when Firefox is closed".

**Comment by pachainti** [comment]
Firefox 85 provides [supercookies protections](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/). You have to close and restart the browser.

**Comment by jonasstrehle** [comment]
> I can't reproduce my IDs with Firefox 85 (Linux). I don't know if it is related to [this](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/), they only mention **cross-site** supercookie protection.

Seems like the latest version of Firefox is no longer vulnerable to this attack scenario. Good to know, thank you!

**Comment by evoactivity** [comment]
I can't reproduce for Firefox 85 (Windows), the demo gives me different id's

**Comment by pachainti** [comment]
Please read [here](https://github.com/jonasstrehle/supercookie/issues/3).
