### ISSUE TITLE
Brave and firefox 85+ are not affected by supercookies

### ISSUE THREAD

**Issue by pachainti** [jonasstrehle/supercookie#3]
Hi,
brave browser and firefox, since [85+](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/), are both not affected by supercookies.

**Comment by jonasstrehle** [comment]
Thank you. I've added Brave to the Readme and updated the entry for Firefox.

**Comment by pachainti** [comment]
Hi,
I made some further evaluation:

- Brave: the protection works well on GNU/Linux, but not on windows 10 2004 and android 9 and 10. However, it offers a different fingerprint in incognito mode on all these platforms.
- Firefox: the protection works well on GNU/Linux and android 9 and 10, but on windows 10 2004 (sometimes it works while other not).
If you confirm this, I can open an issue/bug on the corresponding web sites.

**Comment by jonasstrehle** [comment]
> * If you confirm this, I can open an issue/bug on the corresponding web sites.

Hi, **thank you** for your commitment. 
I can definitely confirm to you that both Brave and Firefox in the latest version are immune to fingerprinting on Linux. That's great news!
Latest version of Firefox (v85.0) on Windows and macOS, however - with the exception that the fingerprint in Incognito mode differs - is still vulnerable. 
According to my own tests, I can also confirm that both browsers are vulnerable on Android 10.

**Comment by pachainti** [comment]
You are welcome and thank you for your work.
I made further tests. On windows 10 2004, firefox 85 and 87 works only sometimes, so I opened a [bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=1691728). On android 9 and 10, firefox works well so I did not open any issue.
Brave provides a different ID in incognito mode on GNU/Linux, windows and android 9-10.

**Comment by pachainti** [comment]
Hi @jonasstrehle, after a further analysis, the developers of brave confirmed that their browser is [not immune to supercookies tracking](https://github.com/brave/brave-browser/issues/14025#issuecomment-776975383). Brave is not able to protect against it in every platform (windows, macOS, gnu/linux, android), so you should update the documentation accordingly.

**Comment by pachainti** [comment]
Is there any update about firefox and brave?

**Comment by pachainti** [comment]
Hello,
could you please update the website with the latest browser version? According to [this](https://privacytests.org/), many browsers should now be immune.
Thank you
