### ISSUE TITLE
node_modules is checked in

### ISSUE THREAD

**Issue by alexanderadam** [jonasstrehle/supercookie#4]
I guess this happened by accident?
This lead to the situation that this repo is over 20MB huge.

Thus I guess you might want to add the directory to [`gitignore`](https://github.com/jonasstrehle/supercookie/blob/main/.gitignore) and [remove the directory from history](https://docs.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history).

**PS:** I case this was added intentionally: why?

**Comment by jonasstrehle** [comment]
Thanks for the hint, I've probably overlooked. Fixed!
