### ISSUE TITLE
Not working)

### ISSUE THREAD

**Issue by 6stprod** [jonasstrehle/supercookie#7]
I got one ID through chrome, another one through Tor. Opera without VPN gave a third identifier, Mozilla also showed another. This nonsense does not work and also does not run on NodeJs))

**Comment by 6stprod** [comment]
Opera vpn and no vpn different IDs

**Comment by jonasstrehle** [comment]
> I got one ID through chrome, another one through Tor. Opera without VPN gave a third identifier, Mozilla also showed another. This nonsense does not work and also does not run on NodeJs))

Fingerprinting is done exactly as expected, but **not** cross-browser.
Please read the docs!
